# Generated by Django 4.1.7 on 2023-04-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0045_userprofile_hide_bundles_bookmarkbundle"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="tag_search",
            field=models.CharField(
                choices=[("strict", "Strict"), ("lax", "Lax"), ("partial", "Partial")],
                default="strict",
                max_length=10,
            ),
        ),
    ]
